"""Keep index maintenance separate from source verification and source claims."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re

from .util import utc_now


def stamp(card: dict) -> dict:
    result = dict(card)
    result["indexed_at"] = utc_now()
    body = str(card.get("body") or "")
    try:
        data = json.loads(body)
        truth = data.get("truth", {}) if isinstance(data, dict) else {}
        checked = truth.get("last_checked_at") or data.get("last_checked_at") if isinstance(data, dict) else None
    except (ValueError, AttributeError):
        match = re.search(r"(?m)^\s*last_checked_at:\s*[\"']?([^\n\"']+)", body)
        checked = match.group(1).strip() if match else None
    result["source_checked_at"] = card.get("source_checked_at") or checked or None
    result["source_mtime_ns"], result["source_sha256"] = None, None
    path = Path(card.get("path") or "")
    try:
        if path.is_absolute() and path.is_file():
            before = path.stat()
            result["source_mtime_ns"] = before.st_mtime_ns
            if before.st_size <= 4_000_000:
                digest = hashlib.sha256(path.read_bytes()).hexdigest()
                after = path.stat()
                if (before.st_mtime_ns, before.st_size) == (after.st_mtime_ns, after.st_size):
                    result["source_sha256"] = digest
    except OSError:
        pass
    return result


def merge_import(conn, card: dict) -> dict:
    """One indexed row per adapter identity, retaining every producer's claim.

    Do not delete pre-existing duplicate rows: lookup groups and exposes them.
    upsert_card returns the canonical ID for evidence generated by the caller.
    """
    families = ({"project-wiki", "project-wiki-export"}, {"issue-tracking", "issue-tracking-export"})
    family = next((values for values in families if card.get("source") in values), None)
    if not family or not card.get("source_ref"):
        return card
    existing = conn.execute("SELECT * FROM cards WHERE source_ref=? AND source IN (?,?) ORDER BY card_id",
                            (card["source_ref"], *sorted(family))).fetchall()
    canonical = existing[0]["card_id"] if existing else card["card_id"]
    # Bootstrap only rows with no provenance; later refreshes replace the same
    # producer/path slot, rather than accumulating repeated index timestamps.
    for row in existing:
        if not conn.execute("SELECT 1 FROM card_provenance WHERE card_id=?", (row["card_id"],)).fetchone():
            old = dict(row)
            conn.execute("INSERT OR IGNORE INTO card_provenance VALUES(?,?,?,?)",
                         (canonical, old["source"], old["path"], json.dumps(old, ensure_ascii=False)))
    conn.execute("INSERT INTO card_provenance VALUES(?,?,?,?) ON CONFLICT(card_id,source,path) DO UPDATE SET body=excluded.body",
                 (canonical, card["source"], card["path"], json.dumps(card, ensure_ascii=False)))
    variants = [json.loads(row[0]) for row in conn.execute("SELECT body FROM card_provenance WHERE card_id=? ORDER BY source,path", (canonical,))]
    merged = dict(card, card_id=canonical)
    if len(variants) > 1:
        conflict = len({(v.get("status"), v.get("body")) for v in variants}) > 1
        merged["body"] = json.dumps({"source_ref": card["source_ref"], "conflict": conflict,
                                     "variants": variants}, ensure_ascii=False, sort_keys=True)
        merged["status"] = "disputed" if conflict else variants[0]["status"]
        merged["confidence"] = min(float(v.get("confidence") or 0) for v in variants)
        merged["aliases"] = sorted({str(a) for v in variants for a in
                                    [v["card_id"], *(v.get("aliases") or json.loads(v.get("aliases_json") or "[]"))]})
        merged["source_checked_at"] = None  # See individual claims; no synthetic verification date.
    return merged
